# Generated by Django 2.1.7 on 2019-05-08 16:15

from django.db import migrations
from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20190508_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=JSONField(default=dict),
        ),
    ]
