# Generated by Django 2.1.7 on 2019-05-25 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20190508_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorited_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='recipe',
        ),
        migrations.AddField(
            model_name='favorite',
            name='recipe',
            field=models.ManyToManyField(to='cookbook.Recipe'),
        ),
    ]
