# Generated by Django 2.1.7 on 2019-05-25 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20190525_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_recipe_favorite', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follows',
        ),
        migrations.AddField(
            model_name='follow',
            name='follows',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
